### ISSUE TITLE
Gnomit should handle editing other things than commit and tag messages

### ISSUE THREAD

**Issue by ptomato** [indie-mirror/gnomit#2]
Currently, if you have Gnomit set as your git `core.editor`, it will open for `git rebase -i`. This will work, but is highlighted wrong. It can be avoided by setting `git config --global sequence.editor` to another editor, so that should be mentioned in the instructions.

A similar problem but without a workaround is when you are doing interactive add with `git add -p` and you choose to edit a patch hunk. Gnomit will log some warnings and then show a blank editor window:
```
Warning: unknown Git commit type encountered in: /path/to/.git/addp-hunk-edit.diff

(Gnomit:3): Gtk-WARNING **: 17:46:13.161: Invalid markup string: Error on line 29: Entity name '(redacted)' is not known
```
This could maybe be solved by allowing Gnomit to "defer" editing of addp-hunk-edit.diff to another editor that you can specify in your git config.

**Comment by aral** [comment]
Thank you for this – my goal is to support both the use cases above. I’ll open separate issues for them to track them.

**Comment by aral** [comment]
git add -p support added in master: https://source.ind.ie/gnome/gnomit/gjs/issues/31

Does this meet your needs, @ptomato?

I’ll look into the rebase message next.

**Comment by ptomato** [comment]
Thanks for the prompt fix! I'll give it a try when it gets released to Flathub.

That said, I usually prefer to edit patch hunks in a full-fledged editor because I use the editor's keybindings to move whole lines around at a time.

**Comment by aral** [comment]
Closing this. I believe the use case was satisfied. Please feel free to reopen if it’s still an issue with the latest release.
