### ISSUE TITLE
Reverse DNS name is the wrong way round

### ISSUE THREAD

**Issue by pwithnall** [indie-mirror/gnomit#3]
https://flathub.org/apps/details/ind.ie.Gnomit

Since your domain name is ind.ie, the reverse DNS name of Gnomit should be `ie.ind.Gnomit`. The incorrect reverse DNS name `ind.ie.Gromit` implies that you own the domain ie.ind.

**Comment by aral** [comment]
Please see https://github.com/flathub/flathub/pull/570#issuecomment-415028848

**Comment by aral** [comment]
(And also https://github.com/flathub/flathub/pull/570#issuecomment-415085996)

**Comment by pwithnall** [comment]
I’m obviously very late to the party here, and nothing I say is going to make the ID for Gromit change, but for the record:
 * Reverse DNS names don’t need to ‘make sense’. They’re an ID, not a name or a brand. If they’re exposed to the user then that’s a usability bug (regardless of what order they’re in).
 * Having an exception for one app provider just because your domain name looks better as ind.ie than reversed as ie.ind confuses matters for everyone, as now people have to remember the rule *and* the exception.
 * One of the points of requiring that the domain name is reversed is to allow future disputes over name ownership to be resolved by looking at domain name ownership. You’d have to resolve disputes by owning the ie.ind domain. Having an exception for the order of your domain name means dispute resolution can never scale (not that I would ever hope it would have to).
 * Your flathub ID should match your app ID, as Nick said. The correct fix here would have been to fix your app ID too.
 * The reason the D-Bus specification (and every other specification which derives from it) says *should* rather than *must* is for backwards compatibility with older applications which were written before we tightened the reverse DNS naming rules up, not forwards compatibility with people who want exceptions in future.
