### ISSUE TITLE
Hg support

### ISSUE THREAD

**Issue by TheRealAgentK** [indie-mirror/gnomit#4]
Hey Aral. I've started to use Gnomit (the pure gjs version from the `bare` branch) for my work with Git since I moved over the Linux a few weeks ago and really like it.

I also use Mercurial for some of my work/projects and tried to hook Gnomit into hg command line as my default editor. That _in general_ works but there are a few quirks re the installation for instance, or specifics of the git format (like expecting a .git directory and a certain text to determine the branch etc). 

I've monkey-patched some of them locally for myself, but I was wondering what your vision for Gnomit is moving forward. I'd be happy to try to implement my fix properly so that Gnomit could be used for both git and hg if you're open to that. Or alternatively if you wanted to keep it git only, I could fork and try to create a separate Mercurial version. Anyway, keen to have a chat.

**Comment by aral** [comment]
Hey Kai, long time no speak; good to hear from you and happy to know you’re enjoying Gnomit :)

I’d like to keep Gnomit as focussed as possible. That said, having an HG version sounds like a great idea. How about a fork (Gnomit HG) that you maintain? That way, we keep things flexible for the future in case we decide to specialise the tools even further to best support the features and culture of the different systems without going for a lowest common denominator approach.

Happy to chat further :) aral@ind.ie

**Comment by TheRealAgentK** [comment]
Cool, that sounds like a plan. Will do a friendly fork for a Gnomit Hg and let you know how I go :) I might ping you via email next week or so to quiz you a bit about how flatpak etc works and what I'd need to do on that end.

**Comment by aral** [comment]
Sounds good to me + feel free to. Open the project in Builder and you can generate the Flatpak from there.

For distribution, I have a script in the root that I run to generate the Flathub distribution and push it automatically. So you should be able to tweak that but you’ll have to also submit it to Flathub for approval first as it’s a separate app. The approval process was not problematic when I did it.
