### ISSUE TITLE
install option does not work

### ISSUE THREAD

**Issue by sonnyp** [indie-mirror/gnomit#9]
The install feature tries to do the following:

`git config --global core.editor '/app/bin/ind.ie.Gnomit'`

`/app/bin/ind.ie.Gnomit` is only a path in the sandbox and `git config ...` would only work on the host 

Maybe it works when the flatpak isn't sandboxed? (Did not try)

Not sure what the intention was. I can submit a PR to fix

**Comment by aral** [comment]
I wonder if that’s why some of the removed permissions were required.

**Comment by sonnyp** [comment]
no - I checked

EDIT: the only permissions I removed are network and dconf related.

**Comment by aral** [comment]
Thanks for looking into it and for the report.

I think the best thing is to just remove that feature. It’s not even mentioned in the readme. I’ll update that for the next release. (Which is going to be under the org.small-tech.Gnomit app id. The current app is going into EOL.)

**Comment by sonnyp** [comment]
Sounds good, I would have also suggested removing it and invite users to do it themselves. 

I'd like to send a PR that opens a window with instructions when you launch the application through the desktop file (and make it visible again). What do you think?

**Comment by aral** [comment]
Install removed in https://github.com/small-tech/gnomit/commit/3feeedd57ef29bf0a910bca71bc413568002cf0f

@sonnyp Would welcome that PR :)
